DROP TABLE IF EXISTS article;

CREATE TABLE article (
  id     INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  title  TINYTEXT NOT NULL,
  body   TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id        INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  username  VARCHAR(255) NOT NULL,
  password  VARCHAR(255) NOT NULL
);